[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "serovar_detector"
dynamic = ["version"]
description = "A pipeline for detecting and typing serovariants of A. pleuropneumoniae"
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
dependencies = [
    "snakemake>=8.0",
    "conda",
    "pandas",
]
authors = [
    {name = "Kasper Thystrup Karstensen", email = "kathka@gmail.com"}
]
maintainers = [
    {name = "Kasper Thystrup Karstensen", email = "kathka@gmail.com"}
]

[project.scripts]
serovar_detector = "serovar_detector.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["serovar_detector"]

[tool.hatch.build.targets.sdist]
include = [
    "/serovar_detector",
]

[tool.hatch.version]
path = "serovar_detector/__version__.py"
