S1:
  - cps1A
  - cps1B
  - cps1C
  - cps1D
S2:
  - cps2A
  - cps2B
  - cps2C
  - cps2D
  - cps2E
  - cps2F
  - cps2G
S3:
  - cps3A
  - cps3B
  - cps3C
  - cps3D
  - cps3E
  - cps3F
  - cps3G
S4:
  - cps4A
  - cps4B
  - cps4C
S5:
  - cps5A
  - cps5B
  - cps5C
S6:
  - cps6A
  - cps2B
  - cps6C
  - cps6D
  - cps6E
  - cps6F
  - cps6G
S7:
  - cps7A
  - cps7B
  - cps7C
  - cps7D
  - cps7E
S8:
  - cps8A
  - cps8B
  - cps8C
  - cps8D
  - cps8E
  - cps8F
  - cps8G
  - cps8H
S9:
  - cps7A
  - cps7B
  - cps9C
  - cps9D
  - cps9E
  - cps9F
S10:
  - cps10A
  - cps10B
  - cps10C
  - cps10D
S11:
  - cps7A
  - cps7B
  - cps9C
  - cps9D
  - cps9E
  - cps11F
S12:
  - cps12A
  - cps12B
  - cps12C
S13:
  - cps2A
  - cps2B
  - cps13C
  - cps13D
  - cps13E
S14:
  - cps14A
  - cps14B1
  - cps14B2
  - cps14B3
  - cps14C
  - cps14D
  - cps14E
  - cps14F
  - cps14G
S15:
  - cps15C
  - cps15B
  - cps15A
S16:
  - cps16A
  - cps16B
  - cps16C
  - cps16D
  - cps16E
  - cps16F
S17:
  - cps17A
  - cps8B
  - cps8C
  - cps17D
  - cps17E
  - cps17F
S18:
  - cps18A
  - cps18B
  - cps18C
S19:
  - cps19A
  - cps19B
  - cps19C
  - cps19D
K2O7:
  - cps8A
  - cps8B
  - cps8C
  - cps2D
  - cps2E
  - cps2F
  - cps2G
